# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93c63d8bcce8f1721e7df1789d79d077edc791119fb52518cb5ee379a11da324f5e4d75fe08777fafa351fed709cb0699f709d2cfb2f36df1cd31147e4162504

test:
  secret_key_base: 344ff5edec02cf7d804fe98cfd4aeaf82a56ca5d43df7b20518b6eaf70e4b7a7741d0cc2d6dd19aa8858f1abb194716e0bae45fc582d404b17b8732b5c0fb95a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
